// [LAW:single-enforcer] Public barrel for the themes module. Name/string policy
// lives in policy.ts; memoized resolver construction (name→resolver and
// transposition) lives in palette-resolvers.ts. rich-js owns palettes,
// hydration, all color math, and the anchor rule — cc-candybar keeps no color
// arithmetic of its own.
export {
  THEME_FLOOR,
  STYLE_FLOOR,
  EXPRESSION_SLOTS,
  isExpression,
  resolveSelection,
  finishSelection,
  decideStyleName,
  resolveStyleSelection,
  effectiveEndcaps,
  effectiveAutoWrap,
  effectivePadding,
  effectiveCharset,
  effectiveColorCompatibility,
  effectiveVariation,
  isVariationName,
  VARIATION_NAMES,
  DEFAULT_VARIATION,
  isEndcaps,
  isCharset,
  isColorCompatibility,
  listResolvablePaletteNames,
  ENDCAPS_SHAPES,
  CHARSETS,
  COLOR_COMPATIBILITIES,
  DEFAULT_CHARSET,
  DEFAULT_COLOR_COMPATIBILITY,
  drawnDepth,
} from "./policy.js";
export type {
  Endcaps,
  Charset,
  ColorCompatibility,
  Selection,
  Decided,
  ExpressionSlot,
  StyleSelection,
  DecidedStyle,
} from "./policy.js";

export {
  paletteForThemeName,
  transposedPalette,
  decideThemeName,
  resolveThemeSelection,
  declaredBasePalette,
  placementPalette,
} from "./palette-resolvers.js";
export type { ThemeSelection, DecidedTheme } from "./palette-resolvers.js";

export {
  DECOR_HUES,
  VARIATIONS,
  OPEN_HUE,
  DECOR_TONES,
  TONE_TINT,
  TONE_RECESS,
  DECOR_VOCABULARY,
  DECOR_CHROMA_SHARE,
  DISTRIBUTIONS,
  DISTRIBUTION_NAMES,
  DEFAULT_DISTRIBUTION,
  placedBy,
  vocabularySelect,
  inBin,
  nearestPoint,
  decorEntryFor,
  paletteRole,
  decorFor,
} from "./decor.js";
export type {
  DecorHue,
  Variation,
  VariationName,
  DecorTone,
  DecorEntry,
  SemanticRole,
  Distribution,
  DistributionName,
  Position,
  PlacedStep,
  Axis,
  AddressStep,
  Address,
  Quantize,
} from "./decor.js";
