#!/usr/bin/env node
// [LAW:one-source-of-truth] The config TYPES are the single source of truth for
// the config grammar; this JSON Schema is DERIVED from them, never hand-authored.
// ts-json-schema-generator walks `RawDslConfig` (the user-file shape — every
// top-level key optional, `layout` sugar or `root` raw) and emits the structural
// contract editors validate against via `$schema`. Because it is generated, the
// schema tracks grammar growth for free: a new VariableDecl kind, a new Direction
// arm, a new ActionDecl shape all flow into the schema on the next run with zero
// schema-authoring work. The committed artifact is regenerated by `build` and
// guarded against drift by `check:schema` (mirrors `check:protocol`).
//
// What this schema does NOT cover (by construction — a JSON Schema cannot):
// cross-references between segments and variables, template cycles, palette-name
// resolution, exactly-one-cache-key. Those are SEMANTIC checks the `lint` CLI
// carries (it runs the real loader). Schema = shape; lint = meaning. Complementary.

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createGenerator } from "ts-json-schema-generator";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// [LAW:one-source-of-truth] The single generation config. Both `gen-schema` and
// `check-schema` import `buildSchema` so the two can never diverge on how the
// schema is produced.
export const SCHEMA_TYPE = "RawDslConfig";
export const SCHEMA_OUT = resolve(ROOT, "schema/cc-candybar.schema.json");
export const SCHEMA_ID =
  "https://raw.githubusercontent.com/promptctl/cc-candybar/main/schema/cc-candybar.schema.json";

export function buildSchema() {
  const generator = createGenerator({
    path: resolve(ROOT, "src/config/dsl-types.ts"),
    tsconfig: resolve(ROOT, "tsconfig.json"),
    type: SCHEMA_TYPE,
    expose: "export",
    topRef: true,
    additionalProperties: false,
    // Deterministic key order so the committed artifact is stable across runs
    // and `check:schema`'s byte-diff is meaningful.
    sortProps: true,
  });
  const schema = generator.createSchema(SCHEMA_TYPE);
  // Annotate the root with JSON Schema meta so editors recognize it and so the
  // published file is self-identifying at its stable URL.
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    $id: SCHEMA_ID,
    title: "cc-candybar config (.cc-candybar.json5)",
    ...schema,
  };
}

export function serializeSchema() {
  return JSON.stringify(buildSchema(), null, 2) + "\n";
}

// Run directly → write the committed artifact.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(SCHEMA_OUT, serializeSchema());
  console.log(`gen-schema: wrote ${SCHEMA_OUT}`);
}
