#!/usr/bin/env tsx
// [LAW:one-source-of-truth] The config loader SCHEMAS are the single source of
// truth for the config grammar; this JSON Schema is DERIVED from them by the same
// declarations the runtime validator interprets (src/config/loader/emit-schema).
// A new VariableDecl kind, a new Direction arm, a new ActionDecl source all flow
// into the schema on the next run with zero schema-authoring work — they are one
// new arm in the loader declaration, read by both interpreters. The committed
// artifact is regenerated by `build` and guarded against drift by `check:schema`
// (mirrors `check:protocol`). The fix for a stale artifact is always
// `pnpm gen:schema`, never editing the JSON by hand.

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { serializeConfigSchema } from "../src/config/loader/emit-schema.js";
import { inheritableSegmentNames } from "../src/config/loader/segments.js";
import { DEFAULT_DSL_CONFIG } from "../src/config/default-dsl-config.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const SCHEMA_OUT = resolve(
  __dirname,
  "..",
  "schema",
  "cc-candybar.schema.json",
);

// [LAW:one-source-of-truth] THE published schema: the loader's grammar with
// the bundled default's segment names as the delta-accepting set — spelled
// once for the generator and the drift check.
export function bundledConfigSchema(): string {
  return serializeConfigSchema(inheritableSegmentNames(DEFAULT_DSL_CONFIG));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(SCHEMA_OUT, bundledConfigSchema());
  console.log(`gen-schema: wrote ${SCHEMA_OUT}`);
}
